// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKtG67vUl_osUIC8XrLG2Ky1Y4Z44nnRU',
    appId: '1:441298344153:web:26df09f9718f1c1f3846c8',
    messagingSenderId: '441298344153',
    projectId: 'signin-demo-b111c',
    authDomain: 'signin-demo-b111c.firebaseapp.com',
    storageBucket: 'signin-demo-b111c.appspot.com',
    measurementId: 'G-SSSCGYD4P8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWPjDzu30jaYJa67AhYhqKPNURzaSPFzc',
    appId: '1:441298344153:android:936cc120fef75ab23846c8',
    messagingSenderId: '441298344153',
    projectId: 'signin-demo-b111c',
    storageBucket: 'signin-demo-b111c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDildqT5bVFvyPSjfCh8CauxYQH8VpAKWQ',
    appId: '1:441298344153:ios:162b063cd00d99573846c8',
    messagingSenderId: '441298344153',
    projectId: 'signin-demo-b111c',
    storageBucket: 'signin-demo-b111c.appspot.com',
    iosClientId: '441298344153-875a9tq022d2ogj75jt78uj3afq5ddf4.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleLoginDemoCs',
  );
}
